/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Windows;

import Classes.Bateau;
import Exception.NumberFormatException;
/*import Classes.Marin;*/
import static Windows.LoginWindow.isNullOrEmpty;
import java.util.StringTokenizer;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Simon
 */
public class InfoBateauWindow extends javax.swing.JFrame {

    /**
     * Creates new form InfoBateauWindow
     */
    CapitainerieWindow CW;
    ImageIcon img;
    Bateau tmpBateau;
    int tmpIndex;

    public InfoBateauWindow(java.awt.Frame parent, Bateau tmp, int index, boolean bool) {
        
        // Initialisation variables --------------------------------------------
        CW = (CapitainerieWindow) parent;
        tmpBateau = tmp;
        tmpIndex = index;
        boolean traitement = bool;

        // ---------------------------------------------------------------------
        
        
        // Initialisation JFrame -----------------------------------------------
        
        initComponents();
        this.setLocationRelativeTo(null);
        this.setLocation(CW.getX() - this.getWidth(), CW.getY());
        this.setResizable(false);
        this.setTitle("Capitainerie - Informations sur bateau entrant");
        
        // ---------------------------------------------------------------------
               
        
        // Display info --------------------------------------------------------
        
        Label_Bateau.setText(tmp.getNom());
        String pavillon = tmp.getPavillon();
        switch (pavillon) {
            case "FR":
                setPavillon("FR");
                break;
            case "UK":
                setPavillon("UK");
                break;
            case "DE":
                setPavillon("DE");
                break;
        }

        Label_Pavillon.setText(null);
        Label_Pavillon.setIcon(getPavillon());

        Label_Emplacement.setText(tmp.getEmplacement());
        
        if(tmp.getTonnage() != 0)
            TextField_Tonnage.setText(Integer.toString(tmp.getTonnage()));
        
        TextField_PortAttache.setText(tmp.getPortAttache());

        autoComboBoxEquipage();
        
        // ---------------------------------------------------------------------
        
        
        // Affichage ou modification -------------------------------------------
        
        if(!traitement)
        {
            Button_Annuler.setText("Quitter");
            TextField_PortAttache.setEditable(traitement);
            TextField_Tonnage.setEditable(traitement);
            Button_Ok.setEnabled(traitement);
            Button_Equipage.setEnabled(traitement);
        }

        // ---------------------------------------------------------------------
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        Button_Equipage = new javax.swing.JButton();
        Button_Ok = new javax.swing.JButton();
        Button_Annuler = new javax.swing.JButton();
        Label_Emplacement = new javax.swing.JLabel();
        Label_Bateau = new javax.swing.JLabel();
        Label_Pavillon = new javax.swing.JLabel();
        TextField_PortAttache = new javax.swing.JTextField();
        TextField_Tonnage = new javax.swing.JTextField();
        ComboBox_Equipage = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel1.setText("Emplacement :");

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel2.setText("Bateau :");

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel3.setText("Pavillon :");

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel4.setText("Port d'attache :");

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel5.setText("Tonnage :");

        Button_Equipage.setText("Equipage");
        Button_Equipage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_EquipageActionPerformed(evt);
            }
        });

        Button_Ok.setText("Ok");
        Button_Ok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_OkActionPerformed(evt);
            }
        });

        Button_Annuler.setText("Annuler");
        Button_Annuler.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_AnnulerActionPerformed(evt);
            }
        });

        Label_Emplacement.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        Label_Emplacement.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Label_Emplacement.setText("/");
        Label_Emplacement.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Label_EmplacementMouseClicked(evt);
            }
        });

        Label_Bateau.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        Label_Bateau.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Label_Bateau.setText("/");

        Label_Pavillon.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        Label_Pavillon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Label_Pavillon.setText("/");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(72, 72, 72)
                        .addComponent(TextField_Tonnage))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(36, 36, 36))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addGap(18, 18, 18)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(Label_Pavillon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Label_Bateau, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Label_Emplacement, javax.swing.GroupLayout.DEFAULT_SIZE, 212, Short.MAX_VALUE))
                            .addComponent(TextField_PortAttache, javax.swing.GroupLayout.PREFERRED_SIZE, 325, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Button_Equipage, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Button_Ok, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Button_Annuler, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(ComboBox_Equipage, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(28, 28, 28))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(Label_Emplacement))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(Label_Bateau))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Label_Pavillon, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(TextField_PortAttache, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(TextField_Tonnage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Button_Equipage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ComboBox_Equipage))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Button_Ok)
                    .addComponent(Button_Annuler))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Button_AnnulerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_AnnulerActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_Button_AnnulerActionPerformed

    private void Button_OkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_OkActionPerformed
        // TODO add your handling code here:
        if (isNullOrEmpty(TextField_Tonnage.getText()) || isNullOrEmpty(TextField_PortAttache.getText())) {
            JOptionPane.showMessageDialog(new JFrame(), "Compléter tous les champs", "Erreur", JOptionPane.ERROR_MESSAGE);
            return;
        } 
        else 
        {
            try {
                if(isNumeric(TextField_Tonnage.getText()))
                {
                    tmpBateau.setTonnage(Integer.parseInt(TextField_Tonnage.getText()));
                
                    tmpBateau.setPortAttache(TextField_PortAttache.getText());

                    CW.vBateauAmarré.set(tmpIndex, tmpBateau);

                    CW.insertListBateau();

                    this.dispose();
                }
                else
                {
                    throw new NumberFormatException("Le tonnage rentré n'est pas bon.");
                }
                
            } catch (NumberFormatException ex) {
                ex.Affiche();
            }
            
            
        }
    }//GEN-LAST:event_Button_OkActionPerformed

    private void Button_EquipageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_EquipageActionPerformed
        // TODO add your handling code here:

//        tmpBateau.setTonnage(Integer.parseInt(TextField_Tonnage.getText()));
        tmpBateau.setPortAttache(TextField_PortAttache.getText());

        CW.vBateauAmarré.set(tmpIndex, tmpBateau);

        EquipageWindow ew = new EquipageWindow(this, true);
        ew.setVisible(true);
    }//GEN-LAST:event_Button_EquipageActionPerformed

    private void Label_EmplacementMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Label_EmplacementMouseClicked
        // TODO add your handling code here:
        TextField_PortAttache.setText("Paris");
        TextField_Tonnage.setText("15");
    }//GEN-LAST:event_Label_EmplacementMouseClicked

    private void setPavillon(String pavillon) {
        img = new ImageIcon(new ImageIcon("images/" + pavillon + ".png").getImage().getScaledInstance(Label_Pavillon.getWidth() / 2, Label_Pavillon.getHeight(), 20));
    }

    private ImageIcon getPavillon() {
        return img;
    }

    public void autoComboBoxEquipage() {
        
        ComboBox_Equipage.removeAllItems();
        
        if (tmpBateau.getEquipage().getAUnEquipage()) {
            ComboBox_Equipage.addItem(tmpBateau.getEquipage().getCapitainerie().getFonction() + " : " + tmpBateau.getEquipage().getCapitainerie().getNom());

            if (tmpBateau.getEquipage().getSecond() != null) {
                ComboBox_Equipage.addItem(tmpBateau.getEquipage().getSecond().getFonction() + " : " + tmpBateau.getEquipage().getSecond().getNom());
            }

            if (tmpBateau.getEquipage().getEquipage() != null) {
                for (int i = 0; i < tmpBateau.getEquipage().getEquipage().size(); i++) {
                    ComboBox_Equipage.addItem(tmpBateau.getEquipage().getEquipage().get(i).getFonction() + " : " + tmpBateau.getEquipage().getEquipage().get(i).getNom());
                }
            }
        }
    }
    
    public static boolean isNumeric(final String str) throws NumberFormatException
    {

        // null or empty
        if (str == null || str.length() == 0) {
            return false;
        }

        for (char c : str.toCharArray()) {
            if (!Character.isDigit(c)) {
                return false;
            }
        }

        return true;

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InfoBateauWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InfoBateauWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InfoBateauWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InfoBateauWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                InfoBateauWindow dialog = new InfoBateauWindow(new javax.swing.JFrame(), null, 0, false);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Button_Annuler;
    private javax.swing.JButton Button_Equipage;
    private javax.swing.JButton Button_Ok;
    private javax.swing.JComboBox<String> ComboBox_Equipage;
    private javax.swing.JLabel Label_Bateau;
    private javax.swing.JLabel Label_Emplacement;
    private javax.swing.JLabel Label_Pavillon;
    private javax.swing.JTextField TextField_PortAttache;
    private javax.swing.JTextField TextField_Tonnage;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    // End of variables declaration//GEN-END:variables
}
